-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 09:58:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema feed_reader
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feed_reader
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feed_reader` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `feed_reader` ;

-- -----------------------------------------------------
-- Table `cryptofeed`.`Feeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feed_reader`.`Feeds` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `url` BLOB NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cryptofeed`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feed_reader`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `feeds` INT NULL,
  `Feeds_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `Feeds_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Users_Feeds_idx` (`Feeds_id` ASC) ,
  CONSTRAINT `fk_Users_Feeds`
    FOREIGN KEY (`Feeds_id`)
    REFERENCES `cryptofeed`.`Feeds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
